# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ test ]
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven

      - name: Build with Maven
        id: maven-build-step
        run: mvn -B package --file pom.xml

      - name: cURL AxiosJS
        uses: indiesdev/curl@v1
        with:
          url: https://autograding-be.herokuapp.com/build-outputs
          method: 'POST'
          accept: 200,201,204
          headers: '{ "Content-Type" : "application/json" }'
          body: ${{ format('{{\"studentId\":\"{0}\","output\":\"{1}\"}}', '74144', steps.maven-build-step.outputs) }}


 # '{ "studentId": "74144",  "output": "tefna jfjnwaofj woaifjwaiofj woaijf owai" }'
#        '{ "studentId": "74144",  "job": "devops" }'
