name: CI for sending solution request

on:
  pull_request:
    types:
      - opened
    branches: [ main ]
  
jobs:
  build:
    if: startsWith(github.head_ref, 'zad2/')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Send request
        uses: satak/webrequest-action@master
        with:
          url: https://autograding-be.herokuapp.com/solution
          method: POST
          payload: >
            {\
            "studentId": "${{ secrets.AIS_ID }}",\
            "gitUserName": "${{ github.actor }}",\
            "repositoryUrl": "${{ github.repositoryUrl }}",\
            "branchName": "${{ github.head_ref }}",\
            "pullRequestId": "${{ github.ref }}",\
            "language": "java"\
            }
